[package]
name = "javm-exec"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "JAR v3 execution engine: PVM interpreter, recompiler, memory, gas. No cap awareness."

[dependencies]
thiserror = { workspace = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
libc = "0.2"
memoffset = "0.9"

[dev-dependencies]
proptest = { workspace = true }
