[package]
name = "bench-ecrecover"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }
nub-rt = { workspace = true }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("none"))'] }
