[package]
name = "bench-goldilocks-mul"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gp = { package = "bench-goldilocks-poseidon2", path = "../goldilocks-poseidon2" }
subsoil = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("none"))'] }
